# list of paths to directories that should be crawled
paths: ["../repo-to-crawl"]
# stdout or file(json)
output: stdout
# if output is file, choose directory
output_dir: outputs
# auto or one of the supported languages for specific repo
lang_mode: go
# should the output JSON be indented
indent_json: true
# ignore paths
ignore: ["extern"]
single_file: ../repo-to-crawl/venus-gateway/proofevent/proof_event.go # for example, replace with different one